[metadata]
name = Leetcode

[options]
python_requires = >= 3.13.0
packages = find:
install_requires =
    fastapi[standard] >= 0.115.6

[options.packages.find]
exclude = tests

[options.extras_require]
dev =
    pre-commit >= 4.0.1
    pre-commit-hooks >= 5.0.0
    flake8 >= 7.1.1
    isort[colors] >= 5.13.2
    black >= 24.10.0
    bandit[toml] >= 1.8.0
    coverage >= 7.6.8
    pytest >= 8.3.3
    pytest-mock >= 3.14.0
    pip-tools >= 7.4.1
    pytest-cov >= 6.0.0
    yamllint >= 1.35.1

[flake8]
max-line-length = 80
extend-ignore = E203
